/*
 * Created on 26 Jan 2017 ( Time 08:55:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "campaign"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="campaign", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Campaign.countAll", query="SELECT COUNT(x) FROM Campaign x" )
} )
public class Campaign implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="parentid", length=18)
    private String     parentid     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;

    @Column(name="expectedrevenue")
    private Double     expectedrevenue ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastreferenceddate")
    private Date       lastreferenceddate ;

    @Column(name="amountwonopportunities")
    private Double     amountwonopportunities ;

    @Column(name="numberofcontacts")
    private Integer    numberofcontacts ;

    @Temporal(TemporalType.DATE)
    @Column(name="publishdate__c")
    private Date       publishdateC ;

    @Column(name="numbersent")
    private Double     numbersent   ;

    @Column(name="expectedresponse")
    private Double     expectedresponse ;

    @Column(name="name", length=80)
    private String     name         ;

    @Column(name="description", length=2147483647)
    private String     description  ;

    @Column(name="numberofconvertedleads")
    private Integer    numberofconvertedleads ;

    @Column(name="isactive")
    private Boolean    isactive     ;

    @Temporal(TemporalType.DATE)
    @Column(name="enddate")
    private Date       enddate      ;

    @Temporal(TemporalType.DATE)
    @Column(name="lastactivitydate")
    private Date       lastactivitydate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastmodifieddate")
    private Date       lastmodifieddate ;

    @Column(name="stock_image__c", length=255)
    private String     stockImage   ;

    @Column(name="sfid", length=18)
    private String     sfid         ;

    @Temporal(TemporalType.DATE)
    @Column(name="startdate")
    private Date       startdate    ;

    @Column(name="actualcost")
    private Double     actualcost   ;

    @Column(name="amountallopportunities")
    private Double     amountallopportunities ;

    @Column(name="status", length=40)
    private String     status       ;

    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;

    @Column(name="budgetedcost")
    private Double     budgetedcost ;

    @Column(name="numberofleads")
    private Integer    numberofleads ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;

    @Column(name="numberofwonopportunities")
    private Integer    numberofwonopportunities ;

    @Column(name="ownerid", length=18)
    private String     ownerid      ;

    @Column(name="isdeleted")
    private Boolean    isdeleted    ;

    @Column(name="lastmodifiedbyid", length=18)
    private String     lastmodifiedbyid ;

    @Column(name="type", length=40)
    private String     type         ;

    @Column(name="campaignmemberrecordtypeid", length=18)
    private String     campaignmemberrecordtypeid ;

    @Column(name="numberofresponses")
    private Integer    numberofresponses ;

    @Column(name="image__c", length=255)
    private String     image        ;

    @Column(name="createdbyid", length=18)
    private String     createdbyid  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastvieweddate")
    private Date       lastvieweddate ;

    @Column(name="numberofopportunities")
    private Integer    numberofopportunities ;

    @Column(name="pic__c", length=1300)
    private String     pic          ;

    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;

    @Column(name="campaignpage__c", length=255)
    private String     campaignpage ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Campaign()
    {
		super();
    }

    public Campaign update(Campaign a) {
		this.id = a.id;
        this.parentid = a.parentid;
        this.systemmodstamp = a.systemmodstamp;
        this.expectedrevenue = a.expectedrevenue;
        this.lastreferenceddate = a.lastreferenceddate;
        this.amountwonopportunities = a.amountwonopportunities;
        this.numberofcontacts = a.numberofcontacts;
        this.publishdateC = a.publishdateC;
        this.numbersent = a.numbersent;
        this.expectedresponse = a.expectedresponse;
        this.name = a.name;
        this.description = a.description;
        this.numberofconvertedleads = a.numberofconvertedleads;
        this.isactive = a.isactive;
        this.enddate = a.enddate;
        this.lastactivitydate = a.lastactivitydate;
        this.lastmodifieddate = a.lastmodifieddate;
        this.stockImage = a.stockImage;
        this.sfid = a.sfid;
        this.startdate = a.startdate;
        this.actualcost = a.actualcost;
        this.amountallopportunities = a.amountallopportunities;
        this.status = a.status;
        this.hcErr = a.hcErr;
        this.budgetedcost = a.budgetedcost;
        this.numberofleads = a.numberofleads;
        this.createddate = a.createddate;
        this.numberofwonopportunities = a.numberofwonopportunities;
        this.ownerid = a.ownerid;
        this.isdeleted = a.isdeleted;
        this.lastmodifiedbyid = a.lastmodifiedbyid;
        this.type = a.type;
        this.campaignmemberrecordtypeid = a.campaignmemberrecordtypeid;
        this.numberofresponses = a.numberofresponses;
        this.image = a.image;
        this.createdbyid = a.createdbyid;
        this.lastvieweddate = a.lastvieweddate;
        this.numberofopportunities = a.numberofopportunities;
        this.pic = a.pic;
        this.hcLastop = a.hcLastop;
        this.campaignpage = a.campaignpage;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : parentid ( varchar ) 
    public void setParentid( String parentid )
    {
        this.parentid = parentid;
    }
    public String getParentid()
    {
        return this.parentid;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : expectedrevenue ( float8 ) 
    public void setExpectedrevenue( Double expectedrevenue )
    {
        this.expectedrevenue = expectedrevenue;
    }
    public Double getExpectedrevenue()
    {
        return this.expectedrevenue;
    }

    //--- DATABASE MAPPING : lastreferenceddate ( timestamp ) 
    public void setLastreferenceddate( Date lastreferenceddate )
    {
        this.lastreferenceddate = lastreferenceddate;
    }
    public Date getLastreferenceddate()
    {
        return this.lastreferenceddate;
    }

    //--- DATABASE MAPPING : amountwonopportunities ( float8 ) 
    public void setAmountwonopportunities( Double amountwonopportunities )
    {
        this.amountwonopportunities = amountwonopportunities;
    }
    public Double getAmountwonopportunities()
    {
        return this.amountwonopportunities;
    }

    //--- DATABASE MAPPING : numberofcontacts ( int4 ) 
    public void setNumberofcontacts( Integer numberofcontacts )
    {
        this.numberofcontacts = numberofcontacts;
    }
    public Integer getNumberofcontacts()
    {
        return this.numberofcontacts;
    }

    //--- DATABASE MAPPING : publishdate__c ( date ) 
    public void setPublishdateC( Date publishdateC )
    {
        this.publishdateC = publishdateC;
    }
    public Date getPublishdateC()
    {
        return this.publishdateC;
    }

    //--- DATABASE MAPPING : numbersent ( float8 ) 
    public void setNumbersent( Double numbersent )
    {
        this.numbersent = numbersent;
    }
    public Double getNumbersent()
    {
        return this.numbersent;
    }

    //--- DATABASE MAPPING : expectedresponse ( float8 ) 
    public void setExpectedresponse( Double expectedresponse )
    {
        this.expectedresponse = expectedresponse;
    }
    public Double getExpectedresponse()
    {
        return this.expectedresponse;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : description ( text ) 
    public void setDescription( String description )
    {
        this.description = description;
    }
    public String getDescription()
    {
        return this.description;
    }

    //--- DATABASE MAPPING : numberofconvertedleads ( int4 ) 
    public void setNumberofconvertedleads( Integer numberofconvertedleads )
    {
        this.numberofconvertedleads = numberofconvertedleads;
    }
    public Integer getNumberofconvertedleads()
    {
        return this.numberofconvertedleads;
    }

    //--- DATABASE MAPPING : isactive ( bool ) 
    public void setIsactive( Boolean isactive )
    {
        this.isactive = isactive;
    }
    public Boolean getIsactive()
    {
        return this.isactive;
    }

    //--- DATABASE MAPPING : enddate ( date ) 
    public void setEnddate( Date enddate )
    {
        this.enddate = enddate;
    }
    public Date getEnddate()
    {
        return this.enddate;
    }

    //--- DATABASE MAPPING : lastactivitydate ( date ) 
    public void setLastactivitydate( Date lastactivitydate )
    {
        this.lastactivitydate = lastactivitydate;
    }
    public Date getLastactivitydate()
    {
        return this.lastactivitydate;
    }

    //--- DATABASE MAPPING : lastmodifieddate ( timestamp ) 
    public void setLastmodifieddate( Date lastmodifieddate )
    {
        this.lastmodifieddate = lastmodifieddate;
    }
    public Date getLastmodifieddate()
    {
        return this.lastmodifieddate;
    }

    //--- DATABASE MAPPING : stock_image__c ( varchar ) 
    public void setStockImage( String stockImage )
    {
        this.stockImage = stockImage;
    }
    public String getStockImage()
    {
        return this.stockImage;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : startdate ( date ) 
    public void setStartdate( Date startdate )
    {
        this.startdate = startdate;
    }
    public Date getStartdate()
    {
        return this.startdate;
    }

    //--- DATABASE MAPPING : actualcost ( float8 ) 
    public void setActualcost( Double actualcost )
    {
        this.actualcost = actualcost;
    }
    public Double getActualcost()
    {
        return this.actualcost;
    }

    //--- DATABASE MAPPING : amountallopportunities ( float8 ) 
    public void setAmountallopportunities( Double amountallopportunities )
    {
        this.amountallopportunities = amountallopportunities;
    }
    public Double getAmountallopportunities()
    {
        return this.amountallopportunities;
    }

    //--- DATABASE MAPPING : status ( varchar ) 
    public void setStatus( String status )
    {
        this.status = status;
    }
    public String getStatus()
    {
        return this.status;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : budgetedcost ( float8 ) 
    public void setBudgetedcost( Double budgetedcost )
    {
        this.budgetedcost = budgetedcost;
    }
    public Double getBudgetedcost()
    {
        return this.budgetedcost;
    }

    //--- DATABASE MAPPING : numberofleads ( int4 ) 
    public void setNumberofleads( Integer numberofleads )
    {
        this.numberofleads = numberofleads;
    }
    public Integer getNumberofleads()
    {
        return this.numberofleads;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : numberofwonopportunities ( int4 ) 
    public void setNumberofwonopportunities( Integer numberofwonopportunities )
    {
        this.numberofwonopportunities = numberofwonopportunities;
    }
    public Integer getNumberofwonopportunities()
    {
        return this.numberofwonopportunities;
    }

    //--- DATABASE MAPPING : ownerid ( varchar ) 
    public void setOwnerid( String ownerid )
    {
        this.ownerid = ownerid;
    }
    public String getOwnerid()
    {
        return this.ownerid;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : lastmodifiedbyid ( varchar ) 
    public void setLastmodifiedbyid( String lastmodifiedbyid )
    {
        this.lastmodifiedbyid = lastmodifiedbyid;
    }
    public String getLastmodifiedbyid()
    {
        return this.lastmodifiedbyid;
    }

    //--- DATABASE MAPPING : type ( varchar ) 
    public void setType( String type )
    {
        this.type = type;
    }
    public String getType()
    {
        return this.type;
    }

    //--- DATABASE MAPPING : campaignmemberrecordtypeid ( varchar ) 
    public void setCampaignmemberrecordtypeid( String campaignmemberrecordtypeid )
    {
        this.campaignmemberrecordtypeid = campaignmemberrecordtypeid;
    }
    public String getCampaignmemberrecordtypeid()
    {
        return this.campaignmemberrecordtypeid;
    }

    //--- DATABASE MAPPING : numberofresponses ( int4 ) 
    public void setNumberofresponses( Integer numberofresponses )
    {
        this.numberofresponses = numberofresponses;
    }
    public Integer getNumberofresponses()
    {
        return this.numberofresponses;
    }

    //--- DATABASE MAPPING : image__c ( varchar ) 
    public void setImage( String image )
    {
        this.image = image;
    }
    public String getImage()
    {
        return this.image;
    }

    //--- DATABASE MAPPING : createdbyid ( varchar ) 
    public void setCreatedbyid( String createdbyid )
    {
        this.createdbyid = createdbyid;
    }
    public String getCreatedbyid()
    {
        return this.createdbyid;
    }

    //--- DATABASE MAPPING : lastvieweddate ( timestamp ) 
    public void setLastvieweddate( Date lastvieweddate )
    {
        this.lastvieweddate = lastvieweddate;
    }
    public Date getLastvieweddate()
    {
        return this.lastvieweddate;
    }

    //--- DATABASE MAPPING : numberofopportunities ( int4 ) 
    public void setNumberofopportunities( Integer numberofopportunities )
    {
        this.numberofopportunities = numberofopportunities;
    }
    public Integer getNumberofopportunities()
    {
        return this.numberofopportunities;
    }

    //--- DATABASE MAPPING : pic__c ( varchar ) 
    public void setPic( String pic )
    {
        this.pic = pic;
    }
    public String getPic()
    {
        return this.pic;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : campaignpage__c ( varchar ) 
    public void setCampaignpage( String campaignpage )
    {
        this.campaignpage = campaignpage;
    }
    public String getCampaignpage()
    {
        return this.campaignpage;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(parentid);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(expectedrevenue);
        sb.append("|");
        sb.append(lastreferenceddate);
        sb.append("|");
        sb.append(amountwonopportunities);
        sb.append("|");
        sb.append(numberofcontacts);
        sb.append("|");
        sb.append(publishdateC);
        sb.append("|");
        sb.append(numbersent);
        sb.append("|");
        sb.append(expectedresponse);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(numberofconvertedleads);
        sb.append("|");
        sb.append(isactive);
        sb.append("|");
        sb.append(enddate);
        sb.append("|");
        sb.append(lastactivitydate);
        sb.append("|");
        sb.append(lastmodifieddate);
        sb.append("|");
        sb.append(stockImage);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(startdate);
        sb.append("|");
        sb.append(actualcost);
        sb.append("|");
        sb.append(amountallopportunities);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(budgetedcost);
        sb.append("|");
        sb.append(numberofleads);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(numberofwonopportunities);
        sb.append("|");
        sb.append(ownerid);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(lastmodifiedbyid);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(campaignmemberrecordtypeid);
        sb.append("|");
        sb.append(numberofresponses);
        sb.append("|");
        sb.append(image);
        sb.append("|");
        sb.append(createdbyid);
        sb.append("|");
        sb.append(lastvieweddate);
        sb.append("|");
        sb.append(numberofopportunities);
        sb.append("|");
        sb.append(pic);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(campaignpage);
        return sb.toString(); 
    } 

}