/*
 * Created on 26 Jan 2017 ( Time 08:55:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "contact"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="contact", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Contact.countAll", query="SELECT COUNT(x) FROM Contact x" )
} )
public class Contact implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="pic__c", length=1300)
    private String     pic          ;

    @Column(name="loyalty_badge__c", length=1300)
    private String     loyaltyBadge ;

    @Column(name="jigsawcontactid", length=20)
    private String     jigsawcontactid ;

    @Column(name="reportstoid", length=18)
    private String     reportstoid  ;

    @Column(name="lastmodifiedbyid", length=18)
    private String     lastmodifiedbyid ;

    @Column(name="isemailbounced")
    private Boolean    isemailbounced ;

    @Column(name="masterrecordid", length=18)
    private String     masterrecordid ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastcurequestdate")
    private Date       lastcurequestdate ;

    @Column(name="email", length=80)
    private String     email        ;

    @Column(name="isdeleted")
    private Boolean    isdeleted    ;

    @Column(name="accountid", length=18)
    private String     accountid    ;

    @Column(name="leadsource", length=40)
    private String     leadsource   ;

    @Column(name="title", length=128)
    private String     title        ;

    @Column(name="othercountry", length=80)
    private String     othercountry ;

    @Column(name="otherstate", length=80)
    private String     otherstate   ;

    @Column(name="name", length=121)
    private String     name         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;

    @Column(name="mailingcity", length=40)
    private String     mailingcity  ;

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate")
    private Date       birthdate    ;

    @Column(name="fbuserid__c", length=50)
    private String     fbuserid     ;

    @Column(name="department", length=80)
    private String     department   ;

    @Column(name="assistantname", length=40)
    private String     assistantname ;

    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;

    @Column(name="otherlongitude")
    private Double     otherlongitude ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="emailbounceddate")
    private Date       emailbounceddate ;

    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastcuupdatedate")
    private Date       lastcuupdatedate ;

    @Column(name="fax", length=40)
    private String     fax          ;

    @Column(name="photourl", length=255)
    private String     photourl     ;

    @Column(name="othercity", length=40)
    private String     othercity    ;

    @Column(name="pictureurl__c", length=255)
    private String     pictureurl   ;

    @Column(name="otherpostalcode", length=20)
    private String     otherpostalcode ;

    @Column(name="homephone", length=40)
    private String     homephone    ;

    @Column(name="mobilephone", length=40)
    private String     mobilephone  ;

    @Column(name="otherphone", length=40)
    private String     otherphone   ;

    @Column(name="otherstreet", length=255)
    private String     otherstreet  ;

    @Temporal(TemporalType.DATE)
    @Column(name="lastactivitydate")
    private Date       lastactivitydate ;

    @Column(name="loyaltyid__c", length=255)
    private String     loyaltyidC   ;

    @Column(name="lastname", length=80)
    private String     lastname     ;

    @Column(name="mailinglatitude")
    private Double     mailinglatitude ;

    @Column(name="mailingpostalcode", length=20)
    private String     mailingpostalcode ;

    @Column(name="preference__c", length=255)
    private String     preference   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastmodifieddate")
    private Date       lastmodifieddate ;

    @Column(name="mailingcountry", length=80)
    private String     mailingcountry ;

    @Column(name="assistantphone", length=40)
    private String     assistantphone ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastvieweddate")
    private Date       lastvieweddate ;

    @Column(name="mailingstreet", length=255)
    private String     mailingstreet ;

    @Column(name="loyalty_points__c")
    private Double     loyaltyPoints ;

    @Column(name="jigsaw", length=20)
    private String     jigsaw       ;

    @Column(name="mailinglongitude")
    private Double     mailinglongitude ;

    @Column(name="mailingstate", length=80)
    private String     mailingstate ;

    @Column(name="otherlatitude")
    private Double     otherlatitude ;

    @Column(name="emailbouncedreason", length=255)
    private String     emailbouncedreason ;

    @Column(name="password__c", length=255)
    private String     password     ;

    @Column(name="description", length=2147483647)
    private String     description  ;

    @Column(name="size__c", length=255)
    private String     size         ;

    @Column(name="gender__c", length=255)
    private String     gender       ;

    @Column(name="ownerid", length=18)
    private String     ownerid      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;

    @Column(name="salutation", length=40)
    private String     salutation   ;

    @Column(name="firstname", length=40)
    private String     firstname    ;

    @Column(name="createdbyid", length=18)
    private String     createdbyid  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastreferenceddate")
    private Date       lastreferenceddate ;

    @Column(name="sfid", length=18)
    private String     sfid         ;

    @Column(name="phone", length=40)
    private String     phone        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Contact()
    {
		super();
    }

    public Contact update(Contact a) {
		this.id = a.id;
        this.pic = a.pic;
        this.loyaltyBadge = a.loyaltyBadge;
        this.jigsawcontactid = a.jigsawcontactid;
        this.reportstoid = a.reportstoid;
        this.lastmodifiedbyid = a.lastmodifiedbyid;
        this.isemailbounced = a.isemailbounced;
        this.masterrecordid = a.masterrecordid;
        this.lastcurequestdate = a.lastcurequestdate;
        this.email = a.email;
        this.isdeleted = a.isdeleted;
        this.accountid = a.accountid;
        this.leadsource = a.leadsource;
        this.title = a.title;
        this.othercountry = a.othercountry;
        this.otherstate = a.otherstate;
        this.name = a.name;
        this.systemmodstamp = a.systemmodstamp;
        this.mailingcity = a.mailingcity;
        this.birthdate = a.birthdate;
        this.fbuserid = a.fbuserid;
        this.department = a.department;
        this.assistantname = a.assistantname;
        this.hcLastop = a.hcLastop;
        this.otherlongitude = a.otherlongitude;
        this.emailbounceddate = a.emailbounceddate;
        this.hcErr = a.hcErr;
        this.lastcuupdatedate = a.lastcuupdatedate;
        this.fax = a.fax;
        this.photourl = a.photourl;
        this.othercity = a.othercity;
        this.pictureurl = a.pictureurl;
        this.otherpostalcode = a.otherpostalcode;
        this.homephone = a.homephone;
        this.mobilephone = a.mobilephone;
        this.otherphone = a.otherphone;
        this.otherstreet = a.otherstreet;
        this.lastactivitydate = a.lastactivitydate;
        this.loyaltyidC = a.loyaltyidC;
        this.lastname = a.lastname;
        this.mailinglatitude = a.mailinglatitude;
        this.mailingpostalcode = a.mailingpostalcode;
        this.preference = a.preference;
        this.lastmodifieddate = a.lastmodifieddate;
        this.mailingcountry = a.mailingcountry;
        this.assistantphone = a.assistantphone;
        this.lastvieweddate = a.lastvieweddate;
        this.mailingstreet = a.mailingstreet;
        this.loyaltyPoints = a.loyaltyPoints;
        this.jigsaw = a.jigsaw;
        this.mailinglongitude = a.mailinglongitude;
        this.mailingstate = a.mailingstate;
        this.otherlatitude = a.otherlatitude;
        this.emailbouncedreason = a.emailbouncedreason;
        this.password = a.password;
        this.description = a.description;
        this.size = a.size;
        this.gender = a.gender;
        this.ownerid = a.ownerid;
        this.createddate = a.createddate;
        this.salutation = a.salutation;
        this.firstname = a.firstname;
        this.createdbyid = a.createdbyid;
        this.lastreferenceddate = a.lastreferenceddate;
        this.sfid = a.sfid;
        this.phone = a.phone;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pic__c ( varchar ) 
    public void setPic( String pic )
    {
        this.pic = pic;
    }
    public String getPic()
    {
        return this.pic;
    }

    //--- DATABASE MAPPING : loyalty_badge__c ( varchar ) 
    public void setLoyaltyBadge( String loyaltyBadge )
    {
        this.loyaltyBadge = loyaltyBadge;
    }
    public String getLoyaltyBadge()
    {
        return this.loyaltyBadge;
    }

    //--- DATABASE MAPPING : jigsawcontactid ( varchar ) 
    public void setJigsawcontactid( String jigsawcontactid )
    {
        this.jigsawcontactid = jigsawcontactid;
    }
    public String getJigsawcontactid()
    {
        return this.jigsawcontactid;
    }

    //--- DATABASE MAPPING : reportstoid ( varchar ) 
    public void setReportstoid( String reportstoid )
    {
        this.reportstoid = reportstoid;
    }
    public String getReportstoid()
    {
        return this.reportstoid;
    }

    //--- DATABASE MAPPING : lastmodifiedbyid ( varchar ) 
    public void setLastmodifiedbyid( String lastmodifiedbyid )
    {
        this.lastmodifiedbyid = lastmodifiedbyid;
    }
    public String getLastmodifiedbyid()
    {
        return this.lastmodifiedbyid;
    }

    //--- DATABASE MAPPING : isemailbounced ( bool ) 
    public void setIsemailbounced( Boolean isemailbounced )
    {
        this.isemailbounced = isemailbounced;
    }
    public Boolean getIsemailbounced()
    {
        return this.isemailbounced;
    }

    //--- DATABASE MAPPING : masterrecordid ( varchar ) 
    public void setMasterrecordid( String masterrecordid )
    {
        this.masterrecordid = masterrecordid;
    }
    public String getMasterrecordid()
    {
        return this.masterrecordid;
    }

    //--- DATABASE MAPPING : lastcurequestdate ( timestamp ) 
    public void setLastcurequestdate( Date lastcurequestdate )
    {
        this.lastcurequestdate = lastcurequestdate;
    }
    public Date getLastcurequestdate()
    {
        return this.lastcurequestdate;
    }

    //--- DATABASE MAPPING : email ( varchar ) 
    public void setEmail( String email )
    {
        this.email = email;
    }
    public String getEmail()
    {
        return this.email;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : accountid ( varchar ) 
    public void setAccountid( String accountid )
    {
        this.accountid = accountid;
    }
    public String getAccountid()
    {
        return this.accountid;
    }

    //--- DATABASE MAPPING : leadsource ( varchar ) 
    public void setLeadsource( String leadsource )
    {
        this.leadsource = leadsource;
    }
    public String getLeadsource()
    {
        return this.leadsource;
    }

    //--- DATABASE MAPPING : title ( varchar ) 
    public void setTitle( String title )
    {
        this.title = title;
    }
    public String getTitle()
    {
        return this.title;
    }

    //--- DATABASE MAPPING : othercountry ( varchar ) 
    public void setOthercountry( String othercountry )
    {
        this.othercountry = othercountry;
    }
    public String getOthercountry()
    {
        return this.othercountry;
    }

    //--- DATABASE MAPPING : otherstate ( varchar ) 
    public void setOtherstate( String otherstate )
    {
        this.otherstate = otherstate;
    }
    public String getOtherstate()
    {
        return this.otherstate;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : mailingcity ( varchar ) 
    public void setMailingcity( String mailingcity )
    {
        this.mailingcity = mailingcity;
    }
    public String getMailingcity()
    {
        return this.mailingcity;
    }

    //--- DATABASE MAPPING : birthdate ( date ) 
    public void setBirthdate( Date birthdate )
    {
        this.birthdate = birthdate;
    }
    public Date getBirthdate()
    {
        return this.birthdate;
    }

    //--- DATABASE MAPPING : fbuserid__c ( varchar ) 
    public void setFbuserid( String fbuserid )
    {
        this.fbuserid = fbuserid;
    }
    public String getFbuserid()
    {
        return this.fbuserid;
    }

    //--- DATABASE MAPPING : department ( varchar ) 
    public void setDepartment( String department )
    {
        this.department = department;
    }
    public String getDepartment()
    {
        return this.department;
    }

    //--- DATABASE MAPPING : assistantname ( varchar ) 
    public void setAssistantname( String assistantname )
    {
        this.assistantname = assistantname;
    }
    public String getAssistantname()
    {
        return this.assistantname;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : otherlongitude ( float8 ) 
    public void setOtherlongitude( Double otherlongitude )
    {
        this.otherlongitude = otherlongitude;
    }
    public Double getOtherlongitude()
    {
        return this.otherlongitude;
    }

    //--- DATABASE MAPPING : emailbounceddate ( timestamp ) 
    public void setEmailbounceddate( Date emailbounceddate )
    {
        this.emailbounceddate = emailbounceddate;
    }
    public Date getEmailbounceddate()
    {
        return this.emailbounceddate;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : lastcuupdatedate ( timestamp ) 
    public void setLastcuupdatedate( Date lastcuupdatedate )
    {
        this.lastcuupdatedate = lastcuupdatedate;
    }
    public Date getLastcuupdatedate()
    {
        return this.lastcuupdatedate;
    }

    //--- DATABASE MAPPING : fax ( varchar ) 
    public void setFax( String fax )
    {
        this.fax = fax;
    }
    public String getFax()
    {
        return this.fax;
    }

    //--- DATABASE MAPPING : photourl ( varchar ) 
    public void setPhotourl( String photourl )
    {
        this.photourl = photourl;
    }
    public String getPhotourl()
    {
        return this.photourl;
    }

    //--- DATABASE MAPPING : othercity ( varchar ) 
    public void setOthercity( String othercity )
    {
        this.othercity = othercity;
    }
    public String getOthercity()
    {
        return this.othercity;
    }

    //--- DATABASE MAPPING : pictureurl__c ( varchar ) 
    public void setPictureurl( String pictureurl )
    {
        this.pictureurl = pictureurl;
    }
    public String getPictureurl()
    {
        return this.pictureurl;
    }

    //--- DATABASE MAPPING : otherpostalcode ( varchar ) 
    public void setOtherpostalcode( String otherpostalcode )
    {
        this.otherpostalcode = otherpostalcode;
    }
    public String getOtherpostalcode()
    {
        return this.otherpostalcode;
    }

    //--- DATABASE MAPPING : homephone ( varchar ) 
    public void setHomephone( String homephone )
    {
        this.homephone = homephone;
    }
    public String getHomephone()
    {
        return this.homephone;
    }

    //--- DATABASE MAPPING : mobilephone ( varchar ) 
    public void setMobilephone( String mobilephone )
    {
        this.mobilephone = mobilephone;
    }
    public String getMobilephone()
    {
        return this.mobilephone;
    }

    //--- DATABASE MAPPING : otherphone ( varchar ) 
    public void setOtherphone( String otherphone )
    {
        this.otherphone = otherphone;
    }
    public String getOtherphone()
    {
        return this.otherphone;
    }

    //--- DATABASE MAPPING : otherstreet ( varchar ) 
    public void setOtherstreet( String otherstreet )
    {
        this.otherstreet = otherstreet;
    }
    public String getOtherstreet()
    {
        return this.otherstreet;
    }

    //--- DATABASE MAPPING : lastactivitydate ( date ) 
    public void setLastactivitydate( Date lastactivitydate )
    {
        this.lastactivitydate = lastactivitydate;
    }
    public Date getLastactivitydate()
    {
        return this.lastactivitydate;
    }

    //--- DATABASE MAPPING : loyaltyid__c ( varchar ) 
    public void setLoyaltyidC( String loyaltyidC )
    {
        this.loyaltyidC = loyaltyidC;
    }
    public String getLoyaltyidC()
    {
        return this.loyaltyidC;
    }

    //--- DATABASE MAPPING : lastname ( varchar ) 
    public void setLastname( String lastname )
    {
        this.lastname = lastname;
    }
    public String getLastname()
    {
        return this.lastname;
    }

    //--- DATABASE MAPPING : mailinglatitude ( float8 ) 
    public void setMailinglatitude( Double mailinglatitude )
    {
        this.mailinglatitude = mailinglatitude;
    }
    public Double getMailinglatitude()
    {
        return this.mailinglatitude;
    }

    //--- DATABASE MAPPING : mailingpostalcode ( varchar ) 
    public void setMailingpostalcode( String mailingpostalcode )
    {
        this.mailingpostalcode = mailingpostalcode;
    }
    public String getMailingpostalcode()
    {
        return this.mailingpostalcode;
    }

    //--- DATABASE MAPPING : preference__c ( varchar ) 
    public void setPreference( String preference )
    {
        this.preference = preference;
    }
    public String getPreference()
    {
        return this.preference;
    }

    //--- DATABASE MAPPING : lastmodifieddate ( timestamp ) 
    public void setLastmodifieddate( Date lastmodifieddate )
    {
        this.lastmodifieddate = lastmodifieddate;
    }
    public Date getLastmodifieddate()
    {
        return this.lastmodifieddate;
    }

    //--- DATABASE MAPPING : mailingcountry ( varchar ) 
    public void setMailingcountry( String mailingcountry )
    {
        this.mailingcountry = mailingcountry;
    }
    public String getMailingcountry()
    {
        return this.mailingcountry;
    }

    //--- DATABASE MAPPING : assistantphone ( varchar ) 
    public void setAssistantphone( String assistantphone )
    {
        this.assistantphone = assistantphone;
    }
    public String getAssistantphone()
    {
        return this.assistantphone;
    }

    //--- DATABASE MAPPING : lastvieweddate ( timestamp ) 
    public void setLastvieweddate( Date lastvieweddate )
    {
        this.lastvieweddate = lastvieweddate;
    }
    public Date getLastvieweddate()
    {
        return this.lastvieweddate;
    }

    //--- DATABASE MAPPING : mailingstreet ( varchar ) 
    public void setMailingstreet( String mailingstreet )
    {
        this.mailingstreet = mailingstreet;
    }
    public String getMailingstreet()
    {
        return this.mailingstreet;
    }

    //--- DATABASE MAPPING : loyalty_points__c ( float8 ) 
    public void setLoyaltyPoints( Double loyaltyPoints )
    {
        this.loyaltyPoints = loyaltyPoints;
    }
    public Double getLoyaltyPoints()
    {
        return this.loyaltyPoints;
    }

    //--- DATABASE MAPPING : jigsaw ( varchar ) 
    public void setJigsaw( String jigsaw )
    {
        this.jigsaw = jigsaw;
    }
    public String getJigsaw()
    {
        return this.jigsaw;
    }

    //--- DATABASE MAPPING : mailinglongitude ( float8 ) 
    public void setMailinglongitude( Double mailinglongitude )
    {
        this.mailinglongitude = mailinglongitude;
    }
    public Double getMailinglongitude()
    {
        return this.mailinglongitude;
    }

    //--- DATABASE MAPPING : mailingstate ( varchar ) 
    public void setMailingstate( String mailingstate )
    {
        this.mailingstate = mailingstate;
    }
    public String getMailingstate()
    {
        return this.mailingstate;
    }

    //--- DATABASE MAPPING : otherlatitude ( float8 ) 
    public void setOtherlatitude( Double otherlatitude )
    {
        this.otherlatitude = otherlatitude;
    }
    public Double getOtherlatitude()
    {
        return this.otherlatitude;
    }

    //--- DATABASE MAPPING : emailbouncedreason ( varchar ) 
    public void setEmailbouncedreason( String emailbouncedreason )
    {
        this.emailbouncedreason = emailbouncedreason;
    }
    public String getEmailbouncedreason()
    {
        return this.emailbouncedreason;
    }

    //--- DATABASE MAPPING : password__c ( varchar ) 
    public void setPassword( String password )
    {
        this.password = password;
    }
    public String getPassword()
    {
        return this.password;
    }

    //--- DATABASE MAPPING : description ( text ) 
    public void setDescription( String description )
    {
        this.description = description;
    }
    public String getDescription()
    {
        return this.description;
    }

    //--- DATABASE MAPPING : size__c ( varchar ) 
    public void setSize( String size )
    {
        this.size = size;
    }
    public String getSize()
    {
        return this.size;
    }

    //--- DATABASE MAPPING : gender__c ( varchar ) 
    public void setGender( String gender )
    {
        this.gender = gender;
    }
    public String getGender()
    {
        return this.gender;
    }

    //--- DATABASE MAPPING : ownerid ( varchar ) 
    public void setOwnerid( String ownerid )
    {
        this.ownerid = ownerid;
    }
    public String getOwnerid()
    {
        return this.ownerid;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : salutation ( varchar ) 
    public void setSalutation( String salutation )
    {
        this.salutation = salutation;
    }
    public String getSalutation()
    {
        return this.salutation;
    }

    //--- DATABASE MAPPING : firstname ( varchar ) 
    public void setFirstname( String firstname )
    {
        this.firstname = firstname;
    }
    public String getFirstname()
    {
        return this.firstname;
    }

    //--- DATABASE MAPPING : createdbyid ( varchar ) 
    public void setCreatedbyid( String createdbyid )
    {
        this.createdbyid = createdbyid;
    }
    public String getCreatedbyid()
    {
        return this.createdbyid;
    }

    //--- DATABASE MAPPING : lastreferenceddate ( timestamp ) 
    public void setLastreferenceddate( Date lastreferenceddate )
    {
        this.lastreferenceddate = lastreferenceddate;
    }
    public Date getLastreferenceddate()
    {
        return this.lastreferenceddate;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : phone ( varchar ) 
    public void setPhone( String phone )
    {
        this.phone = phone;
    }
    public String getPhone()
    {
        return this.phone;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(pic);
        sb.append("|");
        sb.append(loyaltyBadge);
        sb.append("|");
        sb.append(jigsawcontactid);
        sb.append("|");
        sb.append(reportstoid);
        sb.append("|");
        sb.append(lastmodifiedbyid);
        sb.append("|");
        sb.append(isemailbounced);
        sb.append("|");
        sb.append(masterrecordid);
        sb.append("|");
        sb.append(lastcurequestdate);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(accountid);
        sb.append("|");
        sb.append(leadsource);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(othercountry);
        sb.append("|");
        sb.append(otherstate);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(mailingcity);
        sb.append("|");
        sb.append(birthdate);
        sb.append("|");
        sb.append(fbuserid);
        sb.append("|");
        sb.append(department);
        sb.append("|");
        sb.append(assistantname);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(otherlongitude);
        sb.append("|");
        sb.append(emailbounceddate);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(lastcuupdatedate);
        sb.append("|");
        sb.append(fax);
        sb.append("|");
        sb.append(photourl);
        sb.append("|");
        sb.append(othercity);
        sb.append("|");
        sb.append(pictureurl);
        sb.append("|");
        sb.append(otherpostalcode);
        sb.append("|");
        sb.append(homephone);
        sb.append("|");
        sb.append(mobilephone);
        sb.append("|");
        sb.append(otherphone);
        sb.append("|");
        sb.append(otherstreet);
        sb.append("|");
        sb.append(lastactivitydate);
        sb.append("|");
        sb.append(loyaltyidC);
        sb.append("|");
        sb.append(lastname);
        sb.append("|");
        sb.append(mailinglatitude);
        sb.append("|");
        sb.append(mailingpostalcode);
        sb.append("|");
        sb.append(preference);
        sb.append("|");
        sb.append(lastmodifieddate);
        sb.append("|");
        sb.append(mailingcountry);
        sb.append("|");
        sb.append(assistantphone);
        sb.append("|");
        sb.append(lastvieweddate);
        sb.append("|");
        sb.append(mailingstreet);
        sb.append("|");
        sb.append(loyaltyPoints);
        sb.append("|");
        sb.append(jigsaw);
        sb.append("|");
        sb.append(mailinglongitude);
        sb.append("|");
        sb.append(mailingstate);
        sb.append("|");
        sb.append(otherlatitude);
        sb.append("|");
        sb.append(emailbouncedreason);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(size);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(ownerid);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(salutation);
        sb.append("|");
        sb.append(firstname);
        sb.append("|");
        sb.append(createdbyid);
        sb.append("|");
        sb.append(lastreferenceddate);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(phone);
        return sb.toString(); 
    } 

}