/*
 * Created on 26 Jan 2017 ( Time 08:55:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "product2"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="product2", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Product2.countAll", query="SELECT COUNT(x) FROM Product2 x" )
} )
public class Product2 implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=255)
    private String     name         ;

    @Column(name="productcode", length=255)
    private String     productcode  ;

    @Column(name="lastmodifiedbyid", length=18)
    private String     lastmodifiedbyid ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastmodifieddate")
    private Date       lastmodifieddate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;

    @Column(name="pic__c", length=1300)
    private String     picC         ;

    @Column(name="sfid", length=18)
    private String     sfid         ;

    @Column(name="image__c", length=255)
    private String     imageC       ;

    @Column(name="productpage__c", length=255)
    private String     productpageC ;

    @Column(name="isactive")
    private Boolean    isactive     ;

    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;

    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;

    @Column(name="description", length=4000)
    private String     description  ;

    @Column(name="family", length=40)
    private String     family       ;

    @Column(name="createdbyid", length=18)
    private String     createdbyid  ;

    @Column(name="isdeleted")
    private Boolean    isdeleted    ;

    @Temporal(TemporalType.DATE)
    @Column(name="publishdate__c")
    private Date       publishdateC ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Product2()
    {
		super();
    }

    public Product2 update(Product2 a) {
		this.id = a.id;
        this.name = a.name;
        this.productcode = a.productcode;
        this.lastmodifiedbyid = a.lastmodifiedbyid;
        this.lastmodifieddate = a.lastmodifieddate;
        this.createddate = a.createddate;
        this.systemmodstamp = a.systemmodstamp;
        this.picC = a.picC;
        this.sfid = a.sfid;
        this.imageC = a.imageC;
        this.productpageC = a.productpageC;
        this.isactive = a.isactive;
        this.hcErr = a.hcErr;
        this.hcLastop = a.hcLastop;
        this.description = a.description;
        this.family = a.family;
        this.createdbyid = a.createdbyid;
        this.isdeleted = a.isdeleted;
        this.publishdateC = a.publishdateC;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : productcode ( varchar ) 
    public void setProductcode( String productcode )
    {
        this.productcode = productcode;
    }
    public String getProductcode()
    {
        return this.productcode;
    }

    //--- DATABASE MAPPING : lastmodifiedbyid ( varchar ) 
    public void setLastmodifiedbyid( String lastmodifiedbyid )
    {
        this.lastmodifiedbyid = lastmodifiedbyid;
    }
    public String getLastmodifiedbyid()
    {
        return this.lastmodifiedbyid;
    }

    //--- DATABASE MAPPING : lastmodifieddate ( timestamp ) 
    public void setLastmodifieddate( Date lastmodifieddate )
    {
        this.lastmodifieddate = lastmodifieddate;
    }
    public Date getLastmodifieddate()
    {
        return this.lastmodifieddate;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : pic__c ( varchar ) 
    public void setPicC( String picC )
    {
        this.picC = picC;
    }
    public String getPicC()
    {
        return this.picC;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : image__c ( varchar ) 
    public void setImageC( String imageC )
    {
        this.imageC = imageC;
    }
    public String getImageC()
    {
        return this.imageC;
    }

    //--- DATABASE MAPPING : productpage__c ( varchar ) 
    public void setProductpageC( String productpageC )
    {
        this.productpageC = productpageC;
    }
    public String getProductpageC()
    {
        return this.productpageC;
    }

    //--- DATABASE MAPPING : isactive ( bool ) 
    public void setIsactive( Boolean isactive )
    {
        this.isactive = isactive;
    }
    public Boolean getIsactive()
    {
        return this.isactive;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : description ( varchar ) 
    public void setDescription( String description )
    {
        this.description = description;
    }
    public String getDescription()
    {
        return this.description;
    }

    //--- DATABASE MAPPING : family ( varchar ) 
    public void setFamily( String family )
    {
        this.family = family;
    }
    public String getFamily()
    {
        return this.family;
    }

    //--- DATABASE MAPPING : createdbyid ( varchar ) 
    public void setCreatedbyid( String createdbyid )
    {
        this.createdbyid = createdbyid;
    }
    public String getCreatedbyid()
    {
        return this.createdbyid;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : publishdate__c ( date ) 
    public void setPublishdateC( Date publishdateC )
    {
        this.publishdateC = publishdateC;
    }
    public Date getPublishdateC()
    {
        return this.publishdateC;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(productcode);
        sb.append("|");
        sb.append(lastmodifiedbyid);
        sb.append("|");
        sb.append(lastmodifieddate);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(picC);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(imageC);
        sb.append("|");
        sb.append(productpageC);
        sb.append("|");
        sb.append(isactive);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(family);
        sb.append("|");
        sb.append(createdbyid);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(publishdateC);
        return sb.toString(); 
    } 

}