/*
 * Created on 26 Jan 2017 ( Time 08:55:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.repository;

import com.heroku.entities.Contact ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for Contact
 * 
 * @author Telosys Tools Generator
 *
 */
public interface ContactRepository extends PagingAndSortingRepository<Contact, Integer> {
		Contact findBySfid(String sfid);


}